services:
  ttsgen:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server-side:/app
      - ./server-side/xtts_cache:/app/xtts_cache
    restart: unless-stopped
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #   depends_on:
  #     - tts-server
  #   restart: unless-stopped
