version: '3.8'

services:
  tts-server:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server-side:/app
      - ./server-side/xtts_cache:/app/xtts_cache
    restart: unless-stopped
